### ISSUE TITLE
Build from source Property 'credentials.username' doesn't have a configured value.

### ISSUE THREAD

**Issue by SugiuraAyano** [CnC-Robert/revanced-cli-script#3]
Using WSL Ubuntu 20.04.4 LTS
Requirements is already done and the error dump is down below.
![image](https://user-images.githubusercontent.com/44806508/173575104-7087aa1b-cb4f-496c-b9d2-92e01418b4e4.png)

**Comment by CnC-Robert** [comment]
How does ~/.gradle/gradle.properties look like?

**Comment by SugiuraAyano** [comment]
It looks like this 
![image](https://user-images.githubusercontent.com/44806508/173620198-5f3533df-dd60-45da-b8ad-d400d914dce8.png)
I referenced revanced build guide

**Comment by CnC-Robert** [comment]
Try setting $LOCALMAVEN to 1 and rerunning the script

**Comment by SugiuraAyano** [comment]
> Try setting $LOCALMAVEN to 1 and rerunning the script

This resolve my issue. Thanks. Will close this now.
